language: r
cache: packages

branches:
  only:
  - master

env:
  global:
    - secure: "JTMa5VlmEduy2c+kyCfZLjrPuRzqr0qy15hWvz2++xuzIb+mjQuC5ue66827LTGJbmAMZNbIhVbTIpWfbKtnUsFpeMKzSxgBqZlXa3ZoWP6DCYkPCRhaIf+UhJjd7tkoQ4UBz0AmagAmnz1JeuSTCkNMtxA3XnHiaf1v1hs3ItWHleftE7NAgUn9T8IWN8UgpWEgGBrw941fB2lnID5HbfuUdjJCo1kYMlorpTHogmEH1OM8FnuFoLxrMOE+y9nPSO2u5cv2hU5kf1u8OMgh7QQemwZspG5CbBSwoBfFmJbGj/sDObE2dVbiQ6j1oa5a6BCEBieanUagaqv0GonmIwAicD4gCZyZT3dnKmxVN5RHFTr/sQ4W5nXQWVX9AZnZ/MN8gD5DUa5nX4YDjMJ+u2Du8iAmuWnW9Bm+JX6egq+teeDwizWz9LiHCrLYkTCRBbXD2IxCf9l1hMCXsHBjZne8eu0VcYvDUT5fswm4ULDAYVLxDmtYfj9OX+9WbLa5773h2JzZvd3vKHZvJHPeOonS8Nic5FdsJD8n1dhYaJrwO+mWUSVHiCxZzem2hQMTnmScFz+0j2OU/m/7pb99DKdWJmPkXzli8lOcIW0rPE82I3XHkm5eLkeWrliGIlycUle8t4VfKQy63oLngwiTJRCtZlNfZO2Fd6hQ/KryRhs="

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
